### ISSUE TITLE
🔗 日报提交 | cookieY/Yearning: Mysql web端sql审核平台

### ISSUE THREAD

**Issue by ishenyi** [d2-projects/d2-awesome#216]
**:hash: 标题** : cookieY/Yearning: Mysql web端sql审核平台

**:page_with_curl: 介绍** : cookieY/Yearning: Mysql web端sql审核平台

**:link: 链接** : [https://github.com/cookieY/Yearning](https://github.com/cookieY/Yearning)

**:pencil2: Markdown**

```
- name: 工具
  list:
  - name: cookieY/Yearning: Mysql web端sql审核平台
    url: https://github.com/cookieY/Yearning
```

**:space_invader: JSON**

``` js
{"name":"cookieY/Yearning: Mysql web端sql审核平台","note":"cookieY/Yearning: Mysql web端sql审核平台","url":"https://github.com/cookieY/Yearning","type":"工具"}
```

> `2018年11月27日` | 来自 Chrome 插件分享
