### ISSUE TITLE
🔗 日报提交 | javascript-algorithms/README.zh-CN.md at master · trekhleb/javascript-algorithms

### ISSUE THREAD

**Issue by ishenyi** [d2-projects/d2-awesome#229]
**:hash: 标题** : javascript-algorithms/README.zh-CN.md at master · trekhleb/javascript-algorithms

**:page_with_curl: 介绍** : javascript-algorithms/README.zh-CN.md at master · trekhleb/javascript-algorithms

**:link: 链接** : [https://github.com/trekhleb/javascript-algorithms/blob/master/README.zh-CN.md](https://github.com/trekhleb/javascript-algorithms/blob/master/README.zh-CN.md)

**:pencil2: Markdown**

```
- name: 分享
  list:
  - name: JavaScript 算法与数据结构
    url: https://github.com/trekhleb/javascript-algorithms/blob/master/README.zh-CN.md
```

**:space_invader: JSON**

``` js
{"name":"javascript-algorithms/README.zh-CN.md at master · trekhleb/javascript-algorithms","note":"javascript-algorithms/README.zh-CN.md at master · trekhleb/javascript-algorithms","url":"https://github.com/trekhleb/javascript-algorithms/blob/master/README.zh-CN.md","type":"分享"}
```

> `2018年11月28日` | 来自 Chrome 插件分享
