### ISSUE TITLE
🔗 日报提交 | 有意思的JSON.parse（）、JSON.stringify（）

### ISSUE THREAD

**Issue by sunhaoxiang** [d2-projects/d2-awesome#30]
**:hash: 标题** : 有意思的JSON.parse（）、JSON.stringify（）

**:link: 链接** : [https://juejin.im/post/5be5b9f8518825512f58ba0e](https://juejin.im/post/5be5b9f8518825512f58ba0e)

**:page_with_curl: 介绍** : 暂无

**:pencil2: Markdown**

```
- name: 分享
  list:
  - name: 有意思的JSON.parse（）、JSON.stringify（）
    url: https://juejin.im/post/5be5b9f8518825512f58ba0e
```

由 iOS12 捷径 APP 自动提交
