### ISSUE TITLE
🔗 日报提交 | JavaScript Prototype(原型) 新手指南 - 前端 - 掘金

### ISSUE THREAD

**Issue by sunhaoxiang** [d2-projects/d2-awesome#31]
**:hash: 标题** : JavaScript Prototype(原型) 新手指南 - 前端 - 掘金

**:link: 链接** : [https://juejin.im/entry/5bea18315188250edf4ad880](https://juejin.im/entry/5bea18315188250edf4ad880)

**:page_with_curl: 介绍** : 暂无

**:pencil2: Markdown**

```
- name: 分享
  list:
  - name: JavaScript Prototype(原型) 新手指南 - 前端 - 掘金
    url: https://juejin.im/entry/5bea18315188250edf4ad880
```

由 iOS12 捷径 APP 自动提交
