### ISSUE TITLE
🔗 日报提交 | iView 发布 3.1.5 版本，更新日志如下： https://www.iviewui.com/docs/guide/update - 修复 ColorPicker 在开启 transfer 时，输入框无法聚焦的问题。#4718 - 修复 Slider 在使用数字输入框时，清空数值报错的问题。#4746 - 修复 AutoComplete 有时无法选中、选中删除瞬间消失等问题。#4750 - 修复 Table 内无法使用单元格组件 Cell 的问题。#4258 - 优化 Switch 样式。#4762 - 沸点 - 掘金

### ISSUE THREAD

**Issue by FairyEver** [d2-projects/d2-awesome#34]
**:hash: 标题** : iView 发布 3.1.5 版本，更新日志如下： https://www.iviewui.com/docs/guide/update - 修复 ColorPicker 在开启 transfer 时，输入框无法聚焦的问题。#4718 - 修复 Slider 在使用数字输入框时，清空数值报错的问题。#4746 - 修复 AutoComplete 有时无法选中、选中删除瞬间消失等问题。#4750 - 修复 Table 内无法使用单元格组件 Cell 的问题。#4258 - 优化 Switch 样式。#4762 - 沸点 - 掘金

**:link: 链接** : [https://juejin.im/pin/5bea205c51882561b8bf569f](https://juejin.im/pin/5bea205c51882561b8bf569f)

**:page_with_curl: 介绍** : 暂无

**:pencil2: Markdown**

```
- name: 开源项目
  list:
  - name: iView 发布 3.1.5 版本，更新日志如下： https://www.iviewui.com/docs/guide/update - 修复 ColorPicker 在开启 transfer 时，输入框无法聚焦的问题。#4718 - 修复 Slider 在使用数字输入框时，清空数值报错的问题。#4746 - 修复 AutoComplete 有时无法选中、选中删除瞬间消失等问题。#4750 - 修复 Table 内无法使用单元格组件 Cell 的问题。#4258 - 优化 Switch 样式。#4762 - 沸点 - 掘金
    url: https://juejin.im/pin/5bea205c51882561b8bf569f
```

由 iOS12 捷径 APP 自动提交
